export const mockProducts = [
  {
    id: 1,
    name: 'Fresh Organic Tomatoes',
    price: 45,
    originalPrice: 60,
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=400&h=400&fit=crop',
    vendor: 'Fresh Valley',
    category: 'vegetables',
    description: 'Fresh, organic tomatoes sourced directly from local farms.',
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: 'Whole Wheat Bread',
    price: 35,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop',
    vendor: 'Local Bakery',
    category: 'bakery',
    description: 'Freshly baked whole wheat bread made with premium ingredients.',
    rating: 4.8,
    reviews: 245,
  },
  {
    id: 3,
    name: 'Free Range Eggs (12)',
    price: 55,
    originalPrice: 70,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4e6cefc888?w=400&h=400&fit=crop',
    vendor: 'Happy Farms',
    category: 'dairy',
    description: 'Fresh free-range eggs from healthy chickens.',
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 4,
    name: 'Organic Spinach Bundle',
    price: 25,
    originalPrice: 40,
    image: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=400&h=400&fit=crop',
    vendor: 'Green Gardens',
    category: 'vegetables',
    description: 'Fresh organic spinach, highly nutritious.',
    rating: 4.6,
    reviews: 92,
  },
  {
    id: 5,
    name: 'Premium Coffee Beans',
    price: 320,
    originalPrice: 450,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
    vendor: 'Coffee Artisans',
    category: 'beverages',
    description: 'Premium arabica coffee beans roasted fresh daily.',
    rating: 4.9,
    reviews: 342,
  },
  {
    id: 6,
    name: 'Greek Yogurt 500g',
    price: 80,
    originalPrice: 110,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop',
    vendor: 'Dairy Fresh',
    category: 'dairy',
    description: 'Creamy Greek yogurt, perfect for breakfast.',
    rating: 4.4,
    reviews: 156,
  },
  {
    id: 7,
    name: 'Fresh Mushrooms 250g',
    price: 65,
    originalPrice: 85,
    image: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c12330?w=400&h=400&fit=crop',
    vendor: 'Forest Harvest',
    category: 'vegetables',
    description: 'Premium fresh mushrooms, farm sourced.',
    rating: 4.5,
    reviews: 78,
  },
  {
    id: 8,
    name: 'Artisan Cheese Pack',
    price: 280,
    originalPrice: 380,
    image: 'https://images.unsplash.com/photo-1452195125335-94eb014375ed?w=400&h=400&fit=crop',
    vendor: 'Cheese Masters',
    category: 'dairy',
    description: 'Selection of premium artisan cheeses.',
    rating: 4.7,
    reviews: 234,
  },
];

export const mockVendors = [
  {
    id: 1,
    name: 'Fresh Valley',
    email: 'contact@freshvalley.com',
    products: [1],
    rating: 4.5,
    reviews: 456,
  },
  {
    id: 2,
    name: 'Local Bakery',
    email: 'info@localbakery.com',
    products: [2],
    rating: 4.8,
    reviews: 789,
  },
];

export const mockDeliveryOrders = [
  {
    id: 'ORD001',
    customerName: 'John Doe',
    address: '123 Main St, Apt 4B',
    items: ['Fresh Tomatoes', 'Bread'],
    status: 'Pending',
    amount: 120,
    distance: '2.5 km',
  },
  {
    id: 'ORD002',
    customerName: 'Jane Smith',
    address: '456 Oak Ave, Suite 200',
    items: ['Eggs', 'Spinach'],
    status: 'Picked-up',
    amount: 150,
    distance: '1.8 km',
  },
  {
    id: 'ORD003',
    customerName: 'Mike Johnson',
    address: '789 Pine Rd',
    items: ['Coffee Beans', 'Yogurt'],
    status: 'Delivered',
    amount: 420,
    distance: '0 km',
  },
];

export const categories = [
  { id: 'all', name: 'All Products' },
  { id: 'vegetables', name: 'Vegetables' },
  { id: 'dairy', name: 'Dairy & Eggs' },
  { id: 'bakery', name: 'Bakery' },
  { id: 'beverages', name: 'Beverages' },
];

export const faqItems = [
  {
    id: 1,
    title: 'How do I place an order?',
    content: 'Browse our products, add items to your cart, and proceed to checkout. Enter your delivery address and pay securely.',
  },
  {
    id: 2,
    title: 'What is the minimum order value?',
    content: 'The minimum order value is ₹100. Orders below this amount cannot be processed.',
  },
  {
    id: 3,
    title: 'How long does delivery take?',
    content: 'Delivery typically takes 30-45 minutes from the time you place the order in our service area.',
  },
  {
    id: 4,
    title: 'Can I change my order after placing it?',
    content: 'You can change your order within 5 minutes of placing it. After that, it will enter the preparation phase.',
  },
  {
    id: 5,
    title: 'What payment methods do you accept?',
    content: 'We accept credit/debit cards, digital wallets, UPI, and cash on delivery.',
  },
];
